name: Citybuild
version: 1.0
main: ehrenlos.net.citybuild.Citybuild
api-version: 1.16

commands:
  day:
  night:
  sun:
  rain:
  th:
  fly:
  gm:
  heal:
  invsee:
  playerinfo:
  teleport:
  vanish:
  ender:
  playerhelp:
  msg:
  spawn:
  setwarp:
  warp:
  setspawn:
  duty:
  delwarp: